version: '3'

services:

  php:
    image: phpstorm/php-72-apache-xdebug-27
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
